name: Daily Copilot Metrics Fetch

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  workflow_dispatch: # Allow manual trigger too

jobs:
  fetch-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create metrics directory if not exists
        run: mkdir -p metrics

      - name: Get today's date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Fetch metrics via API
        run: |
          curl -H "Authorization: Bearer ${{ secrets.COPILOT_API_TOKEN }}" \
               -H "Accept: application/json" \
               "https://api.github.com/orgs/${{ vars.COPILOT_ORG }}/team/${{ vars.COPILOT_TEAM }}/copilot/metrics" \
               -o "metrics/metrics-${{ steps.date.outputs.date }}.json"

      - name: Upload metrics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: copilot-metrics-${{ steps.date.outputs.date }}
          path: metrics/metrics-${{ steps.date.outputs.date }}.json
