name: TEST Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "test message"
